services:
  py:
    build:
      context: .
      args:
        USER_ID: ${USER_ID}
        GROUP_ID: ${GROUP_ID}
    volumes:
      - .:/grind
    environment:
      PYTHONPATH: .packages
    working_dir: /grind
    command: python -c 'print("Hello, world!")'
